name: gauge-test-sample-in-github-actions

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Test Job
  execute-gauge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Verify Java
        run: java --version

      - name: Setup & Verify Gauge
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install java --version 0.9.1
          gauge version

      - name: Run Test
        run: gauge run specs

      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: gauge-test-report
          path: reports/html-report

      # - name: Copy test report
      #   run: |
      #     mkdir public
      #     cp -r reports/html-report docs
      #     cd docs
      #     ls -al

      # 以降はテスト結果レポートをGitHub Pagesにデプロイするための準備

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./reports/html-report
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Build Report Job
  # build-report:
  #   runs-on: ubuntu-latest
  #   needs: execute-gauge-test
  #   steps:
  #     - name: Setup Pages
  #       uses: actions/configure-pages@v2
  #     - name: Build with Jekyll
  #       uses: actions/jekyll-build-pages@v1
  #       with:
  #         source: ./reports/html-report
  #         destination: ./_site
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v1

  # Deployment Report Job
  deploy-report:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: execute-gauge-test
    # needs: build-report
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
