name: gauge-test-sample-in-github-actions
on: [push]
jobs:
  execute-gauge-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is gauge test."

      - uses: actions/checkout@v3
      - run: |
          ls -al
          cd .github/workflows/
          ls -al

      # setup java
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: java --version

      # setup gauge
      - run: curl -SsL https://downloads.gauge.org/stable | sh
      - run: gauge install java --version 0.9.1
      - run: gauge version

      # run test
      - run: gauge run specs

      # reporting
      - uses: actions/upload-artifact@v3
        with:
          name: gauge-test-report
          path: reports/html-report
